language: node_js

node_js:
  - "stable"

sudo: false

git:
  depth: 3

addons:
  firefox: "41.0.1"

script: npm run $COMMAND

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm run build

env:
  global:
  - secure: "WYQbfTXYwPfqz7t3ycqpXIDQdZ7C9kQJAP+08OF0cuR8eqhm7HxCiu9LjSNqoLAdlDmc55ygeS16Kn3Oht3zZ/i2Y7Gm75HcQfzUIb1sDv1xVm3aQmqZDJfAQ/r7fN8upBCLii/W8IUkJr1k717MpbdsTerIjyfPOb27hw0kJTM="
  - secure: "Ut9pRqzbVJHxg8vt1Cx0bTv4HAroBkvOLjtHF+11f/OzfNnAORIEPnJFHqGbOTozCPOizmzgwvCGqq9gYL8SakrfiI0wBfaL+lk0ub/FPuJ1+hwrLDU0Ju4O5reL0OSu0JB+OTmXfILuRQQkD9/7uwUEbLDFId4phSq3cz1UsK0="
  - secure: "MiufQQKR/EBoS7kcau/I7oYenVilysEqwx37zdgLEKlEUe3SxVOe31uLZv/bhfLNZiRuLAfmIOZmhLGnhMf0LaBzR2yC5qhBxrVHcAiTuS3q6zxpzEf02jnu+hACvj1kJJEPjpOLpEVx7ghWL4McEO0qLbdtSbQlm2IkOX1ONg0="

  matrix:
  - COMMAND=eslint
  - COMMAND=unit-tests
  - CLIENT=node COMMAND=test-pouchdb
  - CLIENT=node COMMAND=test-pouchdb-minimum
  - CLIENT=node SERVER_ARGS=--in-memory COMMAND=test-pouchdb
  - CLIENT=node SERVER_ARGS=--sqlite COMMAND=test-pouchdb

  # Test in firefox/phantomjs running on travis
  - CLIENT=selenium:firefox COMMAND=test-pouchdb
  - CLIENT=selenium:phantomjs COMMAND=test-pouchdb

  # Test against the couchdb harness
  - COMMAND=test-couchdb

matrix:
  allow_failures:
  - env: COMMAND=test-couchdb
  - env: CLIENT=selenium:phantomjs COMMAND=test-pouchdb

branches:
  only:
  - master
